name: Push_Docs.yml

on:
  push:
    branches:
      - master
      - gh-pages
      - update

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container: gyorvaripeter/container:latest
    steps:
      - uses: actions/checkout@v2
      - run: make doc
      - name: Push git subdir as branch
        uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: DOCS/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
